floors = []
floors.append('Floor1')
floors.append('Floor2')
floors.append('test')
rooms = []
rooms.append(('Floor2', 'Room2'))
rooms.append(('Floor2', 'Room4'))
rooms.append(('test', 'a'))
rooms.append(('test', 'b'))
rooms.append(('test', 'h'))
rooms.append(('test', 'u'))
rooms.append(('Floor1', 'Room1'))
rooms.append(('Floor1', 'Room3'))
rooms.append(('Floor1', 'Room5'))
devices = []
devices.append(('test', 'a', '1'))
devices.append(('test', 'a', '2'))
devices.append(('test', 'h', '5'))
devices.append(('test', 'b', '6'))
devices.append(('test', 'h', '6'))
devices.append(('test', 'b', '3'))
devices.append(('test', 'b', '5'))
devices.append(('test', 'b', '4'))
devices.append(('test', 'u', '7'))
