groups = []
groups.append((0, 1, 'Group1'))
groups.append((0, 2, 'Group2'))
groups.append((0, 3, 'Group3'))
groups.append((0, 4, 'Group4'))
groups.append((0, 5, 'Group5'))
groups.append((0, 6, 'Group6'))
groups.append((0, 7, 'Group7'))
groups.append((0, 15, 'Grp'))
groups.append((1, 8, 'Group8'))
groups.append((1, 23, 'Group15'))
groups.append((2, 9, 'Group9'))
groups.append((3, 10, 'Group10'))
groups.append((4, 11, 'Group11'))
groups.append((5, 12, 'Group12'))
groups.append((6, 13, 'Group13'))
groups.append((7, 14, 'Group'))
groups.append((15, 16, 'Init1'))
groups.append((15, 17, 'Init2'))
groups.append((15, 18, 'Init3'))
groups.append((15, 19, 'Init4'))
groups.append((15, 20, 'Init5'))
groups.append((15, 21, 'Init6'))
groups.append((15, 22, 'Init7'))
devices = []
devices.append((0, 'dev', 'Stuff', ('Electrical Outlet', 0, 0, 'Undefined')))
devices.append((0, '1', 'DeviceTest', 'Switch'))
devices.append((1, '1', 'DeviceTest', 'Dimmer'))
devices.append((1, '2', 'None', 'Empty'))
devices.append((3, '2', 'DeviceTest', 'Dimmer'))
devices.append((15, '1', 'DeviceTest', 'Dimmer'))
devices.append((15, '2', 'DeviceTest', 'Dimmer'))
devices.append((15, '3', 'DeviceTest', 'Dimmer'))
devices.append((15, '4', 'DeviceTest', 'Dimmer'))
devices.append((15, '5', 'DeviceTest', 'Dimmer'))
devices.append((15, '6', 'DeviceTest', 'Dimmer'))
devices.append((15, '7', 'DeviceTest', 'Dimmer'))
