groups = []
groups.append((0, 1, 'Group1'))
groups.append((0, 2, 'Group2'))
groups.append((0, 3, 'Group3'))
groups.append((0, 15, 'Group4'))
groups.append((0, 16, 'Group5'))
groups.append((0, 6, 'Group6'))
groups.append((0, 7, 'Group7'))
groups.append((5, 12, 'Group12'))
groups.append((6, 13, 'Group13'))
groups.append((1, 8, 'Group8'))
groups.append((2, 9, 'Group9'))
groups.append((3, 10, 'Group10'))
groups.append((4, 11, 'Group11'))
groups.append((7, 14, 'Group'))
devices = []
devices.append((0, 'dev', 'None', 'Empty'))
devices.append((0, '1', 'DeviceTest', 'Switch'))
devices.append((3, '2', 'DeviceTest', 'Dimmer'))
devices.append((1, '1', 'DeviceTest', 'Dimmer'))
